### ISSUE TITLE
libmemcached won't compile anymore on MacOs 13.3.1

### ISSUE THREAD

**Issue by kwach** [Homebrew/formula-patches#884]
```
✗ cat example.cpp
#include <libmemcached-1.0/memcached.h>
int main() {
return 0;
}
```

```
✗ clang++ example.cpp -o main
In file included from example.cpp:2:
/opt/homebrew/Cellar/libmemcached/1.0.18_2/include/libmemcached-1.0/memcached.h:49:12: fatal error: 'tr1/cinttypes' file not found
#  include <tr1/cinttypes>
           ^~~~~~~~~~~~~~~
1 error generated.
```

stat /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/tr1
stat: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/tr1: stat: No such file or directory

Seems that tr1 is not there anymore.
Patch for libmemcached probably needs to be updated

**Comment by Bo98** [comment]
libmemcached is fairly dead at this point, and we probably should have a think what to do with it. [Some other distributions](https://repology.org/project/libmemcached/versions) have switched to `libmemcached-awesome`, which we could probably do as well. Not sure how compatibile it is with the original version.

But you're right this is caused by our patch and we should address that, and the fix seems simple enough as it's from legacy macOS 10.8 compatibility code that we can simply drop that part of the patch now.

A workaround in the meantime I believe is to include any standard C++ header before you include libmemcached.

**Comment by kwach** [comment]
Workaround works.

Shouldn't the patch account for some older Mac OS versions?

I'll give libmemcached-awesome a look, but in the meantime... :D

**Comment by kwach** [comment]
dropping that part of the patch also worked

**Comment by Bo98** [comment]
> Shouldn't the patch account for some older Mac OS versions?

It's only needed for libstdc++, and libc++ has been around since OS X 10.7.

We don't support < 10.11 anymore, so anyone on those systems should not be running current versions of Homebrew anyway.

**Comment by kwach** [comment]
https://github.com/Homebrew/formula-patches/pull/886
